const Plus = require("./PostImages/plus.png");
const Back = require("./PostImages/Back.png");
const Edit = require("./PostImages/edit.png");
const Hide = require("./PostImages/hide.png");
const User = require("./PostImages/User.jpg");
const Image = require("./PostImages/image.png");
const Delete = require("./PostImages/delete.png");
const Remove = require("./PostImages/remove.png");
const Report = require("./PostImages/report.png");
const HideAll = require("./PostImages/hideAll.png");
const WhitePlus = require("./PostImages/whitePlus.png");
const InstagramLogo = require("./Instagram_logo.png");
const SplashScreen = require("./SplashScreen.png");
export { Back, Remove, Edit, Image, Plus, WhitePlus, Delete, Hide, HideAll, Report, User, InstagramLogo, SplashScreen };