const TYPES = {
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",

    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",

    SET_LOADER_VISIBLE: "SET_LOADER_VISIBLE",

    USERNAMEEXIST_SUCCESS: "USERNAMEEXIST_SUCCESS",
    USERNAMEEXIST_FAILURE: "USERNAMEEXIST_FAILURE"
};

export default TYPES;