const TYPES = {
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",

    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",

    SET_LOADER_VISIBLE: "SET_LOADER_VISIBLE",

    USERNAMEEXIST_SUCCESS: "USERNAMEEXIST_SUCCESS",
    USERNAMEEXIST_FAILURE: "USERNAMEEXIST_FAILURE",

    USEREMAILEXIST_SUCCESS: "USEREMAILEXIST_SUCCESS",
    USEREMAILEXIST_FAILURE: "USEREMAILEXIST_FAILURE",

    SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
    SIGNUP_FAILURE: "SIGNUP_FAILURE",

    DOCUMENT_UPLOAD_SUCCESS: "DOCUMENT_UPLOAD_SUCCESS",
    DOCUMENT_UPLOAD_FAILURE: "DOCUMENT_UPLOAD_FAILURE",

    FEEDLIST_SUCCESS: "FEEDLIST_SUCCESS",
    FEEDLIST_FAILURE: "FEEDLIST_FAILURE"

};

export default TYPES;